# Generated by Django 2.0 on 2018-01-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('catcory', models.CharField(max_length=20, null=True)),
                ('counter_price', models.CharField(max_length=20, null=True)),
                ('gradient_price', models.CharField(max_length=20, null=True)),
                ('price_isActived', models.CharField(max_length=20, null=True)),
                ('price_leftTime', models.CharField(max_length=20, null=True)),
                ('detail_data', models.TextField(null=True)),
                ('crawl_time', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
